services:
  - type: web
    name: chat-with-strangers
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.2
