services:
  - type: web
    name: stranger-chat-v2
    env: node
    plan: free
    buildCommand: |
      cd client
      npm install --unsafe-perm=true
      npm run build
    startCommand: node server/index.js
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 18.18.2
