services:
  - type: web
    name: stranger-chat-v2
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.2
